namespace BloodBowl3;

public enum SpecialCard
{
    FriendlyFans = 3,
    SprinklerMalfunction = 5,
    JohnnyWaterboy = 6,
    Heckler = 7,
    RowdyFans = 8,
    EveryoneSAnExpert = 9,
    ExperimentalFootgear = 12,
    TheProtege = 13,
    BadBurger = 14,
    AssassinationAttempt = 15,
    ForWhomTheBellTolls = 16,
    WarpstoneDust = 17,
    RatRace = 18,
    TheMuskOfFear = 19,
    ShamanicJuju = 21,
    StubbornDetermination = 26,
    RakarthSCurseOfPettySpite = 29,
    BadHabits = 31,
    SteelhelmsSportingTonic = 44,
    FungusBrew = 52,
    SidelineInterference = 73,
    MartialTraining = 56,
    WhisperedSecrets = 71,
    AllOutBlitz = 140,
    PreMatchEspionage = 82,
    HiddenBlade = 85,
    SpectacularCatch = 89,
    BurstOfSpeed = 97,
    GuildOfEngineersExperimentalHelmOfFlight = 105,
    GrukTheBearsGauntlet = 112,
    WightStuff = 121,
    WeatherMage = 252,
    Fireball = 253,
    Zap = 254
}
